### ISSUE TITLE
git reset --hard description vague

### ISSUE THREAD

**Issue by niels-bom-md** [git/git-reference#102]
First of all: I could very well be mistaken.

In the git reset --hard section:

> The third option is to go --hard and make your working directory look like the index, unstage files and undo any changes made since the last commit. This is the most dangerous option and not working directory safe. **Any changes not in the index** or have not been commited will be lost.

As the example after this piece of text shows even changes in the index are lost after a git reset --hard. So this text does not seem to be correct.

**Comment by brntbeer** [comment]
I think the problem here is that people often refer to the index as the most up to date version of the files, and not the staging area. 

> The third option is to go --hard and **make your working directory look like the index**, unstage files and undo any changes made since the last commit.

This part is incorrect. Reset hard does not make your working directory look like the index. As mentioned in https://git-scm.com/docs/git-reset, **Resets the index and working tree. Any changes to tracked files in the working tree since <commit> are discarded.**.

You could, in #101, change this section to say:

_The third option is to go --hard and discard your working directory and staged changes by undoing any changes made since the last commit. This is the most dangerous option and is not working directory safe. Any changes not committed will be lost._

I would read that as, "_`git reset --hard HEAD` removes any work that i edited and removes any work that i had in the staging area for good._"

Thanks for pointing this out. Feel free to add that to your existing PR and fix some of the writing. Feel free to re-open this if you want to continue the discussion, but i may be more valid to chat about it over on #101
